name: Build debian
on:
  - push
  - workflow_dispatch

permissions:
  contents: write
  pages: write

concurrency:
  group: build
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  metadata-orig:
    name: Discover orig metadata
    runs-on: ubuntu-22.04

    outputs:
      orig: ${{ steps.matrix.outputs.orig }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: main

      - name: Check out orig
        uses: actions/checkout@v4
        with:
          ref: orig
          path: orig

      - name: Generate orig matrix
        id: matrix
        run: |
          orig="$(./main/.scripts/discover-orig.sh ./main ./orig)"
          echo "orig=${orig}" >> $GITHUB_OUTPUT

  orig:
    name: Generate orig
    runs-on: ubuntu-22.04
    needs:
      - metadata-orig

    strategy:
      matrix:
        orig: ${{ fromJSON(needs.metadata-orig.outputs.orig) }}

    steps:
      - name: Parse metadata
        if: ${{ matrix.orig != 'placeholder' }}
        id: metadata
        run: |
          echo "repo=$(echo ${{ matrix.orig }} | cut -d' ' -f1)" >> $GITHUB_OUTPUT
          echo "repodir=$(echo ${{ matrix.orig }} | cut -d' ' -f1 | sed -e 's/-snapshot$//')" >> $GITHUB_OUTPUT
          echo "gh_fullrepo=$(echo ${{ matrix.orig }} | cut -d' ' -f2)" >> $GITHUB_OUTPUT
          echo "gh_repo=$(echo ${{ matrix.orig }} | cut -d' ' -f2 | cut -d/ -f2)" >> $GITHUB_OUTPUT
          echo "ref=$(echo ${{ matrix.orig }} | cut -d' ' -f3)" >> $GITHUB_OUTPUT

      - name: Check out code
        if: ${{ matrix.orig != 'placeholder' }}
        uses: actions/checkout@v4
        with:
          path: main

      - name: Check out orig
        if: ${{ matrix.orig != 'placeholder' }}
        uses: actions/checkout@v4
        with:
          ref: orig
          path: orig

      - name: Check out source repository
        if: ${{ matrix.orig != 'placeholder' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.metadata.outputs.gh_fullrepo }}
          ref: ${{ steps.metadata.outputs.ref }}
          path: ${{ steps.metadata.outputs.gh_repo }}
          fetch-depth: 0

      - name: Generate orig
        if: ${{ matrix.orig != 'placeholder' }}
        working-directory: ${{ steps.metadata.outputs.gh_repo }}
        run: |
          mkdir -p ../output
          "../main/${{ steps.metadata.outputs.repodir }}/orig.sh" ../output

      - name: Upload source artifacts
        if: ${{ matrix.orig != 'placeholder' }}
        uses: actions/upload-artifact@v3
        with:
          name: orig--${{ steps.metadata.outputs.repo }}
          path: output

  commit-orig:
    name: Commit orig
    runs-on: ubuntu-22.04
    needs:
      - orig

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: main

      - name: Check out orig
        uses: actions/checkout@v4
        with:
          ref: orig
          path: orig

      - name: Download source artifacts
        uses: actions/download-artifact@v3
        with:
          path: new

      - name: Commit orig updates
        run: ./main/.scripts/commit-orig.sh ./orig ./new

      - name: Push orig updates
        working-directory: orig
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push origin orig

  metadata-build:
    name: Discover build metadata
    runs-on: ubuntu-22.04
    needs:
      - commit-orig

    outputs:
      build: ${{ steps.matrix.outputs.build }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: main

      - name: Check out orig
        uses: actions/checkout@v4
        with:
          ref: orig
          path: orig

      - name: Check out deb
        uses: actions/checkout@v4
        with:
          ref: deb
          path: deb

      - name: Generate build matrix
        id: matrix
        run: |
          build="$(./main/.scripts/discover-build.sh ./main ./orig ./deb)"
          echo "build=${build}" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-22.04
    needs:
      - metadata-build

    strategy:
      matrix:
        build: ${{ fromJSON(needs.metadata-build.outputs.build) }}

    steps:
      - name: Check out code
        if: ${{ matrix.build != 'placeholder' }}
        uses: actions/checkout@v4
        with:
          path: main

      - name: Check out orig
        if: ${{ matrix.build != 'placeholder' }}
        uses: actions/checkout@v4
        with:
          ref: orig
          path: orig

      - name: Build
        if: ${{ matrix.build != 'placeholder' }}
        run: |
          ./main/.scripts/build.sh \
            ./main \
            ./orig \
            ./output \
            ${{ matrix.build }}

      - name: Upload build artifacts
        if: ${{ matrix.build != 'placeholder' }}
        uses: actions/upload-artifact@v3
        with:
          name: build--${{ matrix.build }}
          path: output

  commit-build:
    name: Commit build
    runs-on: ubuntu-22.04
    needs:
      - build

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: main

      - name: Check out deb
        uses: actions/checkout@v4
        with:
          ref: deb
          path: deb

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: new

      - name: Commit build updates
        run: ./main/.scripts/commit-build.sh ./deb ./new

      - name: Push build updates
        working-directory: deb
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push origin deb

  create-repos:
    name: Create repositories
    runs-on: ubuntu-22.04
    needs:
      - commit-build

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: main

      - name: Check out deb
        uses: actions/checkout@v4
        with:
          ref: deb
          path: deb

      - name: Create repositories
        run: ./main/.scripts/create-repos.sh ./output ./deb

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: create-repos
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
