name: Build pbuilder chroots
on:
  - push
  - workflow_dispatch

permissions:
  contents: write

concurrency:
  group: build
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  metadata:
    name: Gather build metadata
    runs-on: ubuntu-22.04

    outputs:
      baseurl: ${{ steps.pbuilder-chroots.outputs.baseurl }}
      build_ids: ${{ steps.matrix.outputs.build_ids }}
      deb_repos: ${{ steps.matrix.outputs.deb_repos }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: src

      - name: Check out repositories
        uses: actions/checkout@v3
        with:
          ref: repos
          path: repos

      - name: Install dependencies
        run: sudo apt install -y grep-dctrl

      - name: Detect available pbuilder-chroots
        id: pbuilder-chroots
        run: |
          baseurl="$(./src/.scripts/pbuilder-chroots_baseurl.sh)"
          echo "baseurl=${baseurl}" >> $GITHUB_OUTPUT
          echo "baseurl=${baseurl}" >> $GITHUB_ENV

      - name: Generate build matrixes
        id: matrix
        run: |
          build_ids="$(./src/.scripts/build-ids_matrix.sh ./src ./repos "${baseurl}")"
          echo "build_ids=${build_ids}" >> $GITHUB_OUTPUT

          deb_repos="$(echo "${build_ids}" | jq -cM '{"deb_repo": .build_id | map(split(" ") | .[0]) | unique}')"
          echo "deb_repos=${deb_repos}" >> $GITHUB_OUTPUT

  sources:
    name: "Sources"
    runs-on: ubuntu-22.04
    needs:
      - metadata

    strategy:
      matrix: ${{ fromJSON(needs.metadata.outputs.deb_repos) }}

    steps:
      - name: Debug
        run: echo ${{ matrix.deb_repo }}

  build:
    name: "Build"
    runs-on: ubuntu-22.04
    needs:
      - metadata
      - sources

    strategy:
      matrix: ${{ fromJSON(needs.metadata.outputs.build_ids) }}

    steps:
      - name: Debug
        run: echo ${{ matrix.build_id }}
