name: Build pbuilder chroots
on:
  - push
  - workflow_dispatch

permissions:
  contents: write

concurrency:
  group: build
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  metadata:
    name: Gather build metadata
    runs-on: ubuntu-22.04

    outputs:
      baseurl: ${{ steps.pbuilder-chroots.outputs.baseurl }}
      build_ids: ${{ steps.matrix.outputs.build_ids }}
      deb_repos: ${{ steps.matrix.outputs.deb_repos }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: src

      - name: Check out repositories
        uses: actions/checkout@v3
        with:
          ref: repos
          path: repos

      - name: Install dependencies
        run: sudo apt install -y grep-dctrl

      - name: Detect available pbuilder-chroots
        id: pbuilder-chroots
        run: |
          baseurl="$(./src/.scripts/pbuilder-chroots_baseurl.sh)"
          echo "baseurl=${baseurl}" >> $GITHUB_OUTPUT
          echo "baseurl=${baseurl}" >> $GITHUB_ENV

      - name: Generate build matrixes
        id: matrix
        run: |
          build_ids="$(./src/.scripts/build-ids_matrix.sh ./src ./repos "${baseurl}")"

          deb_repos="$(echo "${build_ids}" | jq -cM '{"deb_repo": .build_id | map(split(" ") | [.[0,2,3]] | join(" ")) | unique}')"
          echo "deb_repos=${deb_repos}" >> $GITHUB_OUTPUT

          build_ids="$(echo "${build_ids}" | jq -cM '{"build_ids": .build_id | map(split(" ") | [.[0,1]] | join(" "))}')"
          echo "build_ids=${build_ids}" >> $GITHUB_OUTPUT

  sources:
    name: "Sources"
    runs-on: ubuntu-22.04
    needs:
      - metadata

    strategy:
      matrix: ${{ fromJSON(needs.metadata.outputs.deb_repos) }}

    steps:
      - name: Split metadata
        id: metadata
        run: |
          echo "name=$(echo ${{ matrix.deb_repo }} | cut -d' ' -f1)" >> GITHUB_OUTPUT
          echo "repository=$(echo ${{ matrix.deb_repo }} | cut -d' ' -f2)" >> GITHUB_OUTPUT
          echo "repository_name=$(echo ${{ matrix.deb_repo }} | cut -d' ' -f2 | cut -d/ -f2)" >> GITHUB_OUTPUT
          echo "ref=$(echo ${{ matrix.deb_repo }} | cut -d' ' -f2)" >> GITHUB_OUTPUT

      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: src

      - name: Check out source repository
        uses: actions/checkout@v3
        with:
          repository: ${{ steps.metadata.outputs.repository }}
          ref: ${{ steps.metadata.outputs.ref }}
          path: ${{ steps.metadata.outputs.repository_name }}

      - name: Debug
        run: |
          echo repository: ${{ steps.metadata.outputs.repository }}
          echo ref: ${{ steps.metadata.outputs.ref }}
          echo path: ${{ steps.metadata.outputs.repository_name }}

  build:
    name: "Build"
    runs-on: ubuntu-22.04
    needs:
      - metadata
      - sources

    strategy:
      matrix: ${{ fromJSON(needs.metadata.outputs.build_ids) }}

    steps:
      - name: Debug
        run: echo ${{ matrix.build_id }}
