name: Build pbuilder chroots
on:
  - push
  - workflow_dispatch

permissions:
  contents: write

concurrency:
  group: build
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  metadata:
    name: Gather build metadata
    runs-on: ubuntu-22.04

    outputs:
      baseurl: ${{ steps.pbuilder-chroots.outputs.baseurl }}
      build_ids: ${{ steps.matrix.outputs.build_ids }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: src

      - name: Check out repositories
        uses: actions/checkout@v3
        with:
          ref: repos
          path: repos

      - name: Detect available pbuilder-chroots
        id: pbuilder-chroots
        run: |
          baseurl="$(./src/.scripts/pbuilder-chroots_baseurl.sh)"
          echo "baseurl=${baseurl}" >> $GITHUB_OUTPUT
          echo "baseurl=${baseurl}" >> $GITHUB_ENV

      - name: Generate build matrixes
        id: matrix
        run: |
          build_ids="$(./src/.scripts/build-ids_matrix.sh ./src ./repos "${baseurl}")"
          echo "build_ids=${build_ids}" >> $GITHUB_OUTPUT

  build:
    name: "Build: ${{ matrix.build_id }}"
    runs-on: ubuntu-22.04
    needs: metadata

    strategy:
      matrix: ${{ fromJSON(needs.metadata.outputs.build_ids) }}

    steps:
      - name: Debug
        run: echo ${{ matrix.build_id }}
